### ISSUE TITLE
There was an error while executing `VBoxManage`

### ISSUE THREAD

**Issue by aikidistas** [GM-Alex/vagrant-winnfsd#28]
Installed this plugin on windows 7 and after trying to vagrant up it gave an error.

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["list", "hostonlyifs"]

Stderr: VBoxManage.exe: error: Failed to create the VirtualBox object!
VBoxManage.exe: error: Code CO_E_SERVER_EXEC_FAILURE (0x80080005) - Server execution failed (extended info not available)
VBoxManage.exe: error: Most likely, the VirtualBox COM server is not running or failed to start.
![capture](https://cloud.githubusercontent.com/assets/1716305/4953252/7857dd14-667e-11e4-9b09-d33888ec98ed.PNG)

**Comment by GM-Alex** [comment]
I don't think that this issue is related to the plugin.
