### ISSUE TITLE
FYI : Error 'No gems found matching "vagrant-vmware-fusion"' at installation

### ISSUE THREAD

**Issue by borisschapira** [GM-Alex/vagrant-winnfsd#33]
FYI, it is possible that you encounter an error during the plugin installation, regarding an unmatched dependancy to  the "vagrant-vmware-fusion" gem :

```
C:\projects> vagrant plugin install vagrant-winnfsd
Installing the 'vagrant-winnfsd' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Net::HTTPNotFound: No gems found matching "vagrant-vmware-fusion" "3.0.1" nil
```

If something like that happen, simply try to run ```vagrant plugin install vagrant-winnfsd``` again. It worked for me and after a quick search, several people encountered the same symptoms.

**Comment by apintocr** [comment]
Thank you @borisschapira :)

**Comment by apintocr** [comment]
@GM-Alex this should go into the Readme :)
