### ISSUE TITLE
Problems using docker container

### ISSUE THREAD

**Issue by janschultecom** [GM-Alex/vagrant-winnfsd#34]
Hi,

I had some trouble getting things work using CoreOs and Docker containers, when mounting a docker path to a coreos path which itself was mounted to the winnfs synced folder. I continuously ran into stale file handle issues. However, if I use tcp instead of udp it works fine. 

Cheers

Jan

**Comment by yannschepens** [comment]
Hi,

I use docker too with a debian machine (my VM), I use a volume container
with is links with my Vagrant synced folder, and i haven't got problem
(currently).

Cheers,

Yann

2015-01-16 9:44 GMT+01:00 Jan Schulte <notifications@github.com>:

> Hi,
>
> I had some trouble getting things work using CoreOs and Docker containers,
> when mounting a docker path to a coreos path which itself was mounted to
> the winnfs synced folder. I continuously ran into stale file handle issues.
> However, if I use tcp instead of udp it works fine.
>
> Cheers
>
> Jan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GM-Alex/vagrant-winnfsd/issues/34>.
>



-- 
Yann Schepens

yann.schepens@gmail.com

**Comment by janschultecom** [comment]
Strange, might be a problem of the limited capabilities of CoreOS then...

**Comment by GM-Alex** [comment]
@janschultecom Are you using Panamax?

**Comment by janschultecom** [comment]
Nope, didn't know that one. Looks very interesting though...

**Comment by GM-Alex** [comment]
The problem is CoreOS itself there is some stuff missing. It's the same for the boot2docker vagrant image.

**Comment by analytik** [comment]
Hi. We're using CoreOS, and we're having this problem more often since we upgraded to vagrant-winnfsd 1.1.0 (from 1.0.10 I think). Halt&up helps. 

I'm not sure if this is CoreOS problem, since boot2docker doesn't use CoreOS.

**Comment by langdead** [comment]
I also came across such issue(win10 + vagrant + coreos + container in coreos).
```
core@core-01 ~ $ rm -rf /proj/gogs/gogs
rm: cannot remove '/proj/gogs/gogs/data': Stale file handle
rm: cannot remove '/proj/gogs/gogs/log': Stale file handle
core@core-01 ~ $ uname -a
Linux core-01 4.6.3-coreos #2 SMP Tue Jul 12 18:22:26 UTC 2016 x86_64 Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz GenuineIntel GNU/Linux
core@core-01 ~ $
```

Now the folder itself can't be removed in either coreos or windows after `vagrant destroy`  the coreos...

**Comment by langdead** [comment]
seemed `rd /Q /S folder_name` in Windows Cmd(as Administrator) can rm the broken folder.

**Comment by langdead** [comment]
seemed `rd /Q /S folder_name` in Windows Cmd(as Administrator) can rm the broken folder.

**Comment by langdead** [comment]
seemed `rd /Q /S folder_name` in Windows Cmd(as Administrator) can rm the broken folder.

**Comment by langdead** [comment]
seemed `rd /Q /S folder_name` in Windows Cmd(as Administrator) can rm the broken folder.

**Comment by langdead** [comment]
seemed `rd /Q /S folder_name` in Windows Cmd(as Administrator) can rm the broken folder.

**Comment by langdead** [comment]
seemed `rd /Q /S folder_name` in Windows Cmd(as Administrator) can rm the broken folder.

**Comment by langdead** [comment]
seemed `rd /Q /S folder_name` in Windows Cmd(as Administrator) can rm the broken folder.

**Comment by langdead** [comment]
seemed `rd /Q /S folder_name` in Windows Cmd(as Administrator) can rm the broken folder.

**Comment by langdead** [comment]
seemed `rd /Q /S folder_name` in Windows Cmd(as Administrator) can rm the broken folder.

**Comment by langdead** [comment]
seemed `rd /Q /S folder_name` in Windows Cmd(as Administrator) can rm the broken folder.

**Comment by langdead** [comment]
seemed `rd /Q /S folder_name` in Windows Cmd(as Administrator) can rm the broken folder.

**Comment by langdead** [comment]
seemed `rd /Q /S folder_name` in Windows Cmd(as Administrator) can rm the broken folder.

**Comment by langdead** [comment]
seemed `rd /Q /S folder_name` in Windows Cmd(as Administrator) can rm the broken folder.

**Comment by langdead** [comment]
seemed `rd /Q /S folder_name` in Windows Cmd(as Administrator) can rm the broken folder.

**Comment by marcharding** [comment]
Can you provide me with a complete test case (Vagrantfile etc.) so i can reproduce this?

**Comment by langdead** [comment]
Hi @marcharding , sorry for replying late!

With follow Vagrantfile that's from https://github.com/coreos/coreos-vagrant/, and adapted according to winnfsd instruction.
- in config.rb, added below
$shared_folders = {'../data' => '/proj'}

- setup gogs
```
mkdir /proj/gogs
docker pull gogs/gogs
docker run --name=gogs -p 10022:22 -p 10080:3000 -v /proj/gogs:/data gogs/gogs
```
- install gogs by opening http://172.28.128.3:10080/. Pls check what's your own IP address from coreos. Choose DB sqlite3, user, pass. Replace all 22 wih 10022, replace all 3000 with 10080, replace all localhost with the IP address.

- stop gogs
`docker stop gogs`

Now you should be not able to rm the folder "/proj/gogs"

Thx very much for your follow up! And nice weekend!

Regards
Langdead

[Vagrantfile.zip](https://github.com/winnfsd/vagrant-winnfsd/files/391697/Vagrantfile.zip)

**Comment by marcharding** [comment]
Hey, i could remove the folder without problems...
