### ISSUE TITLE
Custom winnfsd.exe

### ISSUE THREAD

**Issue by mbrodala** [GM-Alex/vagrant-winnfsd#60]
There seem to be some issues with the bundled `winnfsd.exe` and it seems like [WinNFSd-new](https://bitbucket.org/yannschepens/winnfsd-new) performs a bit better here.

Is there a away to cleanly prefer a local `winnnfsd.exe` over the bundled one?

Disclaimer: I am not actively using this plugin yet but have colleagues which do and noticed this.

**Comment by yannschepens** [comment]
@Alex : Can we repackage the vagrant plugin with the last release of
winnfsd ?

2015-06-26 16:03 GMT+02:00 Mathias Brodala <notifications@github.com>:

> There seem to be some issues with the bundled winnfsd.exe and it seems
> like WinNFSd-new <https://bitbucket.org/yannschepens/winnfsd-new>
> performs a bit better here.
>
> Is there a away to cleanly prefer a local winnnfsd.exe over the bundled
> one?
>
> Disclaimer: I am not actively using this plugin yet but have colleagues
> which do and noticed this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GM-Alex/vagrant-winnfsd/issues/60>.
>



-- 
Yann Schepens

yann.schepens@gmail.com

**Comment by GM-Alex** [comment]
@yannschepens Could you build a new bin with the latest fixes? I have currently some trouble to get VS to work. After that I will update the module.

**Comment by kevinquillen** [comment]
There is a very critical fix for WinNFS here in this custom compile:

https://bitbucket.org/jankowfsky/winnfsd/issue/7/winnfsd-doesnt-always-overwrite-files#comment-18163351

Without it, changes to CSS/SASS were not being sync'd with the guest machine correctly causing all sorts of confusing issues. This .exe corrects the behavior.

**Comment by yannschepens** [comment]
@alex : You can take this release :
https://bitbucket.org/yannschepens/winnfsd-new/downloads/WinNFSd%20-%20xtreamwayz%20-%202.exe

@kevin : Normally, this last release contain the fix ;)

2015-06-29 15:22 GMT+02:00 Kevin <notifications@github.com>:

> There is a very critical fix for WinNFS here in this custom compile:
>
>
> https://bitbucket.org/jankowfsky/winnfsd/issue/7/winnfsd-doesnt-always-overwrite-files#comment-18163351
>
> Without it, changes to CSS/SASS were not being sync'd with the guest
> machine correctly causing all sorts of confusing issues. This .exe corrects
> the behavior.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GM-Alex/vagrant-winnfsd/issues/60#issuecomment-116658145>
> .
>



-- 
Yann Schepens

yann.schepens@gmail.com

**Comment by kevinquillen** [comment]
What is the status on this? Developing on Windows absolutely cannot happen without the sync fix in the executable.

**Comment by marijnotte** [comment]
+1 (we now replace the winnfsd.exe after installation of vagrant-winnfsd because the shipped version contains bugs, but it would be much better if the new version is shipped)

**Comment by GM-Alex** [comment]
New version with update binary is released.

**Comment by kevinquillen** [comment]
Sweet!

**Comment by marijnotte** [comment]
Very cool!
